package com.satgy.embudi.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

@Entity
@Table(name = "userpassword")
public class UserPassword {

    // Isn't autogenerated or autoincremental, is the same that userid
    @Id
    @Column(name = "userpasswordid")
    private Long userPasswordId;

    @ManyToOne
    @JoinColumn(name = "userid", nullable = false, referencedColumnName = "userid", foreignKey=@ForeignKey(name = "FK_UserPassword_User"))
    private User user;

    @NotNull(message = "Please enter the password")
    @Size(min = 0, max = 500, message = "The password must be 0 to 500 characters long")
    @Column(name = "password", nullable = false, length = 500)
    private String password;

    // -------------------------------------------------- GETTERS AND SETTERS --------------------------------------------------------------------

    public Long getUserPasswordId() {
        return userPasswordId;
    }

    public void setUserPasswordId(Long userPasswordId) {
        this.userPasswordId = userPasswordId;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public @NotNull(message = "Please enter the password") @Size(min = 0, max = 500, message = "The password must be 0 to 500 long characters long") String getPassword() {
        return password;
    }

    public void setPassword(@NotNull(message = "Please enter the password") @Size(min = 0, max = 500, message = "The password must be 0 to 500 long characters long") String password) {
        this.password = password;
    }
}
